export const GET_MOVIES_LIST = 'GET_MOVIES_LIST';
export const GET_GENRE_LIST = 'GET_GENRE_LIST';
export const LOADING_TRUE = 'LOADING_TRUE';
export const LOADING_FALSE = 'LOADING_FALSE';
export const IMG_LOADING_FALSE = 'IMG_LOADING_FALSE';
export const IMG_LOADING_TRUE = 'IMG_LOADING_TRUE';